  0%|          | 0/134 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 189, in <module>
    main()
  File "train.py", line 183, in main
    trainer.training(epoch)
  File "train.py", line 85, in training
    output = self.model(image)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/home1/rh254/Domain_Adaptation/configs/ry.deeplab.MUL.vegas/model/deeplab.py", line 29, in forward
    x, low_level_feat = self.backbone(input)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/home1/rh254/Domain_Adaptation/configs/ry.deeplab.MUL.vegas/model/backbone/mobilenet.py", line 119, in forward
    x = self.high_level_features(low_level_feat)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/home1/rh254/Domain_Adaptation/configs/ry.deeplab.MUL.vegas/model/backbone/mobilenet.py", line 63, in forward
    x = x + self.conv(x_pad)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/home1/rh254/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 164.00 MiB (GPU 0; 10.73 GiB total capacity; 4.61 GiB already allocated; 7.56 MiB free; 102.08 MiB cached)

  0%|          | 0/134 [00:24<?, ?it/s]
